// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_VISIONDATA_INTERIORPLATFORM_H_
#define FLATBUFFERS_GENERATED_VISIONDATA_INTERIORPLATFORM_H_

#include "flatbuffers/flatbuffers.h"

namespace InteriorPlatform {

struct Vec3;

struct Vec2;

struct BoundingBox;
struct BoundingBoxBuilder;

struct DetectedObject;
struct DetectedObjectBuilder;

struct HandTracking;
struct HandTrackingBuilder;

struct VisionMessage;
struct VisionMessageBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3(float _x, float _y, float _z)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec2 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;

 public:
  Vec2()
      : x_(0),
        y_(0) {
  }
  Vec2(float _x, float _y)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
};
FLATBUFFERS_STRUCT_END(Vec2, 8);

struct BoundingBox FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef BoundingBoxBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X_MIN = 4,
    VT_Y_MIN = 6,
    VT_X_MAX = 8,
    VT_Y_MAX = 10
  };
  float x_min() const {
    return GetField<float>(VT_X_MIN, 0.0f);
  }
  float y_min() const {
    return GetField<float>(VT_Y_MIN, 0.0f);
  }
  float x_max() const {
    return GetField<float>(VT_X_MAX, 0.0f);
  }
  float y_max() const {
    return GetField<float>(VT_Y_MAX, 0.0f);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X_MIN) &&
           VerifyField<float>(verifier, VT_Y_MIN) &&
           VerifyField<float>(verifier, VT_X_MAX) &&
           VerifyField<float>(verifier, VT_Y_MAX) &&
           verifier.EndTable();
  }
};

struct BoundingBoxBuilder {
  typedef BoundingBox Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_x_min(float x_min) {
    fbb_.AddElement<float>(BoundingBox::VT_X_MIN, x_min, 0.0f);
  }
  void add_y_min(float y_min) {
    fbb_.AddElement<float>(BoundingBox::VT_Y_MIN, y_min, 0.0f);
  }
  void add_x_max(float x_max) {
    fbb_.AddElement<float>(BoundingBox::VT_X_MAX, x_max, 0.0f);
  }
  void add_y_max(float y_max) {
    fbb_.AddElement<float>(BoundingBox::VT_Y_MAX, y_max, 0.0f);
  }
  explicit BoundingBoxBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<BoundingBox> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<BoundingBox>(end);
    return o;
  }
};

inline flatbuffers::Offset<BoundingBox> CreateBoundingBox(
    flatbuffers::FlatBufferBuilder &_fbb,
    float x_min = 0.0f,
    float y_min = 0.0f,
    float x_max = 0.0f,
    float y_max = 0.0f) {
  BoundingBoxBuilder builder_(_fbb);
  builder_.add_y_max(y_max);
  builder_.add_x_max(x_max);
  builder_.add_y_min(y_min);
  builder_.add_x_min(x_min);
  return builder_.Finish();
}

struct DetectedObject FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef DetectedObjectBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_LABEL = 6,
    VT_CONFIDENCE = 8,
    VT_BBOX = 10,
    VT_POSITION_3D = 12
  };
  int32_t id() const {
    return GetField<int32_t>(VT_ID, 0);
  }
  const flatbuffers::String *label() const {
    return GetPointer<const flatbuffers::String *>(VT_LABEL);
  }
  float confidence() const {
    return GetField<float>(VT_CONFIDENCE, 0.0f);
  }
  const InteriorPlatform::BoundingBox *bbox() const {
    return GetPointer<const InteriorPlatform::BoundingBox *>(VT_BBOX);
  }
  const InteriorPlatform::Vec3 *position_3d() const {
    return GetStruct<const InteriorPlatform::Vec3 *>(VT_POSITION_3D);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ID) &&
           VerifyOffset(verifier, VT_LABEL) &&
           verifier.VerifyString(label()) &&
           VerifyField<float>(verifier, VT_CONFIDENCE) &&
           VerifyOffset(verifier, VT_BBOX) &&
           verifier.VerifyTable(bbox()) &&
           VerifyField<InteriorPlatform::Vec3>(verifier, VT_POSITION_3D) &&
           verifier.EndTable();
  }
};

struct DetectedObjectBuilder {
  typedef DetectedObject Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(int32_t id) {
    fbb_.AddElement<int32_t>(DetectedObject::VT_ID, id, 0);
  }
  void add_label(flatbuffers::Offset<flatbuffers::String> label) {
    fbb_.AddOffset(DetectedObject::VT_LABEL, label);
  }
  void add_confidence(float confidence) {
    fbb_.AddElement<float>(DetectedObject::VT_CONFIDENCE, confidence, 0.0f);
  }
  void add_bbox(flatbuffers::Offset<InteriorPlatform::BoundingBox> bbox) {
    fbb_.AddOffset(DetectedObject::VT_BBOX, bbox);
  }
  void add_position_3d(const InteriorPlatform::Vec3 *position_3d) {
    fbb_.AddStruct(DetectedObject::VT_POSITION_3D, position_3d);
  }
  explicit DetectedObjectBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<DetectedObject> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<DetectedObject>(end);
    return o;
  }
};

inline flatbuffers::Offset<DetectedObject> CreateDetectedObject(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    flatbuffers::Offset<flatbuffers::String> label = 0,
    float confidence = 0.0f,
    flatbuffers::Offset<InteriorPlatform::BoundingBox> bbox = 0,
    const InteriorPlatform::Vec3 *position_3d = 0) {
  DetectedObjectBuilder builder_(_fbb);
  builder_.add_position_3d(position_3d);
  builder_.add_bbox(bbox);
  builder_.add_confidence(confidence);
  builder_.add_label(label);
  builder_.add_id(id);
  return builder_.Finish();
}

inline flatbuffers::Offset<DetectedObject> CreateDetectedObjectDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    const char *label = nullptr,
    float confidence = 0.0f,
    flatbuffers::Offset<InteriorPlatform::BoundingBox> bbox = 0,
    const InteriorPlatform::Vec3 *position_3d = 0) {
  auto label__ = label ? _fbb.CreateString(label) : 0;
  return InteriorPlatform::CreateDetectedObject(
      _fbb,
      id,
      label__,
      confidence,
      bbox,
      position_3d);
}

struct HandTracking FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef HandTrackingBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_IS_PINCHING = 4,
    VT_PINCH_POSITION = 6
  };
  bool is_pinching() const {
    return GetField<uint8_t>(VT_IS_PINCHING, 0) != 0;
  }
  const InteriorPlatform::Vec3 *pinch_position() const {
    return GetStruct<const InteriorPlatform::Vec3 *>(VT_PINCH_POSITION);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_IS_PINCHING) &&
           VerifyField<InteriorPlatform::Vec3>(verifier, VT_PINCH_POSITION) &&
           verifier.EndTable();
  }
};

struct HandTrackingBuilder {
  typedef HandTracking Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_is_pinching(bool is_pinching) {
    fbb_.AddElement<uint8_t>(HandTracking::VT_IS_PINCHING, static_cast<uint8_t>(is_pinching), 0);
  }
  void add_pinch_position(const InteriorPlatform::Vec3 *pinch_position) {
    fbb_.AddStruct(HandTracking::VT_PINCH_POSITION, pinch_position);
  }
  explicit HandTrackingBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<HandTracking> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<HandTracking>(end);
    return o;
  }
};

inline flatbuffers::Offset<HandTracking> CreateHandTracking(
    flatbuffers::FlatBufferBuilder &_fbb,
    bool is_pinching = false,
    const InteriorPlatform::Vec3 *pinch_position = 0) {
  HandTrackingBuilder builder_(_fbb);
  builder_.add_pinch_position(pinch_position);
  builder_.add_is_pinching(is_pinching);
  return builder_.Finish();
}

struct VisionMessage FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef VisionMessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TIMESTAMP = 4,
    VT_OBJECTS = 6,
    VT_HANDS = 8
  };
  int64_t timestamp() const {
    return GetField<int64_t>(VT_TIMESTAMP, 0);
  }
  const flatbuffers::Vector<flatbuffers::Offset<InteriorPlatform::DetectedObject>> *objects() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<InteriorPlatform::DetectedObject>> *>(VT_OBJECTS);
  }
  const InteriorPlatform::HandTracking *hands() const {
    return GetPointer<const InteriorPlatform::HandTracking *>(VT_HANDS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_TIMESTAMP) &&
           VerifyOffset(verifier, VT_OBJECTS) &&
           verifier.VerifyVector(objects()) &&
           verifier.VerifyVectorOfTables(objects()) &&
           VerifyOffset(verifier, VT_HANDS) &&
           verifier.VerifyTable(hands()) &&
           verifier.EndTable();
  }
};

struct VisionMessageBuilder {
  typedef VisionMessage Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_timestamp(int64_t timestamp) {
    fbb_.AddElement<int64_t>(VisionMessage::VT_TIMESTAMP, timestamp, 0);
  }
  void add_objects(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<InteriorPlatform::DetectedObject>>> objects) {
    fbb_.AddOffset(VisionMessage::VT_OBJECTS, objects);
  }
  void add_hands(flatbuffers::Offset<InteriorPlatform::HandTracking> hands) {
    fbb_.AddOffset(VisionMessage::VT_HANDS, hands);
  }
  explicit VisionMessageBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<VisionMessage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<VisionMessage>(end);
    return o;
  }
};

inline flatbuffers::Offset<VisionMessage> CreateVisionMessage(
    flatbuffers::FlatBufferBuilder &_fbb,
    int64_t timestamp = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<InteriorPlatform::DetectedObject>>> objects = 0,
    flatbuffers::Offset<InteriorPlatform::HandTracking> hands = 0) {
  VisionMessageBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_hands(hands);
  builder_.add_objects(objects);
  return builder_.Finish();
}

inline flatbuffers::Offset<VisionMessage> CreateVisionMessageDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    int64_t timestamp = 0,
    const std::vector<flatbuffers::Offset<InteriorPlatform::DetectedObject>> *objects = nullptr,
    flatbuffers::Offset<InteriorPlatform::HandTracking> hands = 0) {
  auto objects__ = objects ? _fbb.CreateVector<flatbuffers::Offset<InteriorPlatform::DetectedObject>>(*objects) : 0;
  return InteriorPlatform::CreateVisionMessage(
      _fbb,
      timestamp,
      objects__,
      hands);
}

inline const InteriorPlatform::VisionMessage *GetVisionMessage(const void *buf) {
  return flatbuffers::GetRoot<InteriorPlatform::VisionMessage>(buf);
}

inline const InteriorPlatform::VisionMessage *GetSizePrefixedVisionMessage(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<InteriorPlatform::VisionMessage>(buf);
}

inline bool VerifyVisionMessageBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<InteriorPlatform::VisionMessage>(nullptr);
}

inline bool VerifySizePrefixedVisionMessageBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<InteriorPlatform::VisionMessage>(nullptr);
}

inline void FinishVisionMessageBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<InteriorPlatform::VisionMessage> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedVisionMessageBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<InteriorPlatform::VisionMessage> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace InteriorPlatform

#endif  // FLATBUFFERS_GENERATED_VISIONDATA_INTERIORPLATFORM_H_
