// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace InteriorPlatform
{

using global::System;
using global::System.Collections.Generic;
using Google.FlatBuffers;

public struct BoundingBox : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static BoundingBox GetRootAsBoundingBox(ByteBuffer _bb) { return GetRootAsBoundingBox(_bb, new BoundingBox()); }
  public static BoundingBox GetRootAsBoundingBox(ByteBuffer _bb, BoundingBox obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public BoundingBox __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float XMin { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float YMin { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float XMax { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float YMax { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<InteriorPlatform.BoundingBox> CreateBoundingBox(FlatBufferBuilder builder,
      float x_min = 0.0f,
      float y_min = 0.0f,
      float x_max = 0.0f,
      float y_max = 0.0f) {
    builder.StartTable(4);
    BoundingBox.AddYMax(builder, y_max);
    BoundingBox.AddXMax(builder, x_max);
    BoundingBox.AddYMin(builder, y_min);
    BoundingBox.AddXMin(builder, x_min);
    return BoundingBox.EndBoundingBox(builder);
  }

  public static void StartBoundingBox(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddXMin(FlatBufferBuilder builder, float xMin) { builder.AddFloat(0, xMin, 0.0f); }
  public static void AddYMin(FlatBufferBuilder builder, float yMin) { builder.AddFloat(1, yMin, 0.0f); }
  public static void AddXMax(FlatBufferBuilder builder, float xMax) { builder.AddFloat(2, xMax, 0.0f); }
  public static void AddYMax(FlatBufferBuilder builder, float yMax) { builder.AddFloat(3, yMax, 0.0f); }
  public static Offset<InteriorPlatform.BoundingBox> EndBoundingBox(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<InteriorPlatform.BoundingBox>(o);
  }
};


}
