// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace InteriorPlatform
{

using global::System;
using global::System.Collections.Generic;
using Google.FlatBuffers;

public struct DetectedObject : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static DetectedObject GetRootAsDetectedObject(ByteBuffer _bb) { return GetRootAsDetectedObject(_bb, new DetectedObject()); }
  public static DetectedObject GetRootAsDetectedObject(ByteBuffer _bb, DetectedObject obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DetectedObject __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Label { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLabelBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetLabelBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetLabelArray() { return __p.__vector_as_array<byte>(6); }
  public float Confidence { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public InteriorPlatform.BoundingBox? Bbox { get { int o = __p.__offset(10); return o != 0 ? (InteriorPlatform.BoundingBox?)(new InteriorPlatform.BoundingBox()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public InteriorPlatform.Vec3? Position3d { get { int o = __p.__offset(12); return o != 0 ? (InteriorPlatform.Vec3?)(new InteriorPlatform.Vec3()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartDetectedObject(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddLabel(FlatBufferBuilder builder, StringOffset labelOffset) { builder.AddOffset(1, labelOffset.Value, 0); }
  public static void AddConfidence(FlatBufferBuilder builder, float confidence) { builder.AddFloat(2, confidence, 0.0f); }
  public static void AddBbox(FlatBufferBuilder builder, Offset<InteriorPlatform.BoundingBox> bboxOffset) { builder.AddOffset(3, bboxOffset.Value, 0); }
  public static void AddPosition3d(FlatBufferBuilder builder, Offset<InteriorPlatform.Vec3> position3dOffset) { builder.AddStruct(4, position3dOffset.Value, 0); }
  public static Offset<InteriorPlatform.DetectedObject> EndDetectedObject(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<InteriorPlatform.DetectedObject>(o);
  }
};


}
