// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace InteriorPlatform
{

using global::System;
using global::System.Collections.Generic;
using Google.FlatBuffers;

public struct HandTracking : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static HandTracking GetRootAsHandTracking(ByteBuffer _bb) { return GetRootAsHandTracking(_bb, new HandTracking()); }
  public static HandTracking GetRootAsHandTracking(ByteBuffer _bb, HandTracking obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public HandTracking __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool IsPinching { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public InteriorPlatform.Vec3? PinchPosition { get { int o = __p.__offset(6); return o != 0 ? (InteriorPlatform.Vec3?)(new InteriorPlatform.Vec3()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartHandTracking(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddIsPinching(FlatBufferBuilder builder, bool isPinching) { builder.AddBool(0, isPinching, false); }
  public static void AddPinchPosition(FlatBufferBuilder builder, Offset<InteriorPlatform.Vec3> pinchPositionOffset) { builder.AddStruct(1, pinchPositionOffset.Value, 0); }
  public static Offset<InteriorPlatform.HandTracking> EndHandTracking(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<InteriorPlatform.HandTracking>(o);
  }
};


}
