// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace InteriorPlatform
{

using global::System;
using global::System.Collections.Generic;
using Google.FlatBuffers;

public struct VisionMessage : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static VisionMessage GetRootAsVisionMessage(ByteBuffer _bb) { return GetRootAsVisionMessage(_bb, new VisionMessage()); }
  public static VisionMessage GetRootAsVisionMessage(ByteBuffer _bb, VisionMessage obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public VisionMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long Timestamp { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public InteriorPlatform.DetectedObject? Objects(int j) { int o = __p.__offset(6); return o != 0 ? (InteriorPlatform.DetectedObject?)(new InteriorPlatform.DetectedObject()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ObjectsLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  public InteriorPlatform.HandTracking? Hands { get { int o = __p.__offset(8); return o != 0 ? (InteriorPlatform.HandTracking?)(new InteriorPlatform.HandTracking()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<InteriorPlatform.VisionMessage> CreateVisionMessage(FlatBufferBuilder builder,
      long timestamp = 0,
      VectorOffset objectsOffset = default(VectorOffset),
      Offset<InteriorPlatform.HandTracking> handsOffset = default(Offset<InteriorPlatform.HandTracking>)) {
    builder.StartTable(3);
    VisionMessage.AddTimestamp(builder, timestamp);
    VisionMessage.AddHands(builder, handsOffset);
    VisionMessage.AddObjects(builder, objectsOffset);
    return VisionMessage.EndVisionMessage(builder);
  }

  public static void StartVisionMessage(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddTimestamp(FlatBufferBuilder builder, long timestamp) { builder.AddLong(0, timestamp, 0); }
  public static void AddObjects(FlatBufferBuilder builder, VectorOffset objectsOffset) { builder.AddOffset(1, objectsOffset.Value, 0); }
  public static VectorOffset CreateObjectsVector(FlatBufferBuilder builder, Offset<InteriorPlatform.DetectedObject>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateObjectsVectorBlock(FlatBufferBuilder builder, Offset<InteriorPlatform.DetectedObject>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartObjectsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddHands(FlatBufferBuilder builder, Offset<InteriorPlatform.HandTracking> handsOffset) { builder.AddOffset(2, handsOffset.Value, 0); }
  public static Offset<InteriorPlatform.VisionMessage> EndVisionMessage(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<InteriorPlatform.VisionMessage>(o);
  }
  public static void FinishVisionMessageBuffer(FlatBufferBuilder builder, Offset<InteriorPlatform.VisionMessage> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedVisionMessageBuffer(FlatBufferBuilder builder, Offset<InteriorPlatform.VisionMessage> offset) { builder.FinishSizePrefixed(offset.Value); }
};


}
