# automatically generated by the FlatBuffers compiler, do not modify

# namespace: InteriorPlatform

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BoundingBox(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsBoundingBox(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BoundingBox()
        x.Init(buf, n + offset)
        return x

    # BoundingBox
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BoundingBox
    def XMin(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BoundingBox
    def YMin(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BoundingBox
    def XMax(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BoundingBox
    def YMax(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def BoundingBoxStart(builder): builder.StartObject(4)
def BoundingBoxAddXMin(builder, xMin): builder.PrependFloat32Slot(0, xMin, 0.0)
def BoundingBoxAddYMin(builder, yMin): builder.PrependFloat32Slot(1, yMin, 0.0)
def BoundingBoxAddXMax(builder, xMax): builder.PrependFloat32Slot(2, xMax, 0.0)
def BoundingBoxAddYMax(builder, yMax): builder.PrependFloat32Slot(3, yMax, 0.0)
def BoundingBoxEnd(builder): return builder.EndObject()
