# automatically generated by the FlatBuffers compiler, do not modify

# namespace: InteriorPlatform

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DetectedObject(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsDetectedObject(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DetectedObject()
        x.Init(buf, n + offset)
        return x

    # DetectedObject
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DetectedObject
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DetectedObject
    def Label(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DetectedObject
    def Confidence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # DetectedObject
    def Bbox(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from InteriorPlatform.BoundingBox import BoundingBox
            obj = BoundingBox()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DetectedObject
    def Position3d(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            from InteriorPlatform.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def DetectedObjectStart(builder): builder.StartObject(5)
def DetectedObjectAddId(builder, id): builder.PrependInt32Slot(0, id, 0)
def DetectedObjectAddLabel(builder, label): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(label), 0)
def DetectedObjectAddConfidence(builder, confidence): builder.PrependFloat32Slot(2, confidence, 0.0)
def DetectedObjectAddBbox(builder, bbox): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(bbox), 0)
def DetectedObjectAddPosition3d(builder, position3d): builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(position3d), 0)
def DetectedObjectEnd(builder): return builder.EndObject()
