# automatically generated by the FlatBuffers compiler, do not modify

# namespace: InteriorPlatform

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HandTracking(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsHandTracking(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HandTracking()
        x.Init(buf, n + offset)
        return x

    # HandTracking
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HandTracking
    def IsPinching(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # HandTracking
    def PinchPosition(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from InteriorPlatform.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def HandTrackingStart(builder): builder.StartObject(2)
def HandTrackingAddIsPinching(builder, isPinching): builder.PrependBoolSlot(0, isPinching, 0)
def HandTrackingAddPinchPosition(builder, pinchPosition): builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(pinchPosition), 0)
def HandTrackingEnd(builder): return builder.EndObject()
