# automatically generated by the FlatBuffers compiler, do not modify

# namespace: InteriorPlatform

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VisionMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsVisionMessage(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VisionMessage()
        x.Init(buf, n + offset)
        return x

    # VisionMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VisionMessage
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # VisionMessage
    def Objects(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from InteriorPlatform.DetectedObject import DetectedObject
            obj = DetectedObject()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VisionMessage
    def ObjectsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # VisionMessage
    def ObjectsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # VisionMessage
    def Hands(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from InteriorPlatform.HandTracking import HandTracking
            obj = HandTracking()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def VisionMessageStart(builder): builder.StartObject(3)
def VisionMessageAddTimestamp(builder, timestamp): builder.PrependInt64Slot(0, timestamp, 0)
def VisionMessageAddObjects(builder, objects): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(objects), 0)
def VisionMessageStartObjectsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def VisionMessageAddHands(builder, hands): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(hands), 0)
def VisionMessageEnd(builder): return builder.EndObject()
